//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab29MovieDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieList
    {
        public int ID { get; set; }
        public string TItle { get; set; }
        public string Category { get; set; }
        public int ReleaseYear { get; set; }
        public decimal RatingIMDB { get; set; }
        public string RatingMPAA { get; set; }
    }
}
